python main.py Capture1.PNG
python main.py Capture2.PNG
python main.py Capture3.PNG
python main.py Capture4.PNG
python main.py Capture5.PNG
python main.py Capture6.PNG
python main.py Capture7.PNG
python main.py Capture8.PNG
python main.py Capture9.PNG
python main.py Capture10.PNG
python main.py Capture11.PNG
python main.py Capture12.PNG
python main.py Capture13.PNG
python main.py Capture14.PNG
python main.py Capture15.PNG
python main.py Capture16.PNG
python main.py Capture17.PNG
python main.py Capture18.PNG
python main.py Capture19.PNG
python main.py Capture20.PNG
python main.py Capture21.PNG
python main.py Capture22.PNG
python main.py Capture23.PNG
python main.py Capture24.PNG
python main.py Capture25.PNG
python main.py Capture26.PNG
python main.py Capture27.PNG
python main.py Capture28.PNG
python main.py Capture29.PNG
python main.py Capture30.PNG
python main.py Capture31.PNG
